# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13AIIuTB2QjfBLLojaGAr6iLpgwBOHdXt
"""

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('Read a CSV').getOrCreate()

data = """id,name,city,age,salary
1,Arjun,Hyderabad,25,45000
2,Meera,Chennai,32,52000
3,Rajesh,Bangalore,29,61000
4,Priya,Delhi,22,38000
5,Sanjay,Mumbai,35,72000
"""

with open("employees.csv","w") as f:
    f.write(data)

df = spark.read \
.option("header","true") \
.option("inferSchema","true") \
.csv("employees.csv")

df.show()
df.printSchema()

json_data = [
  {
    "id": 1,
    "name": "Arjun",
    "city": "Hyderabad",
    "age": 25,
    "salary": 45000
  },
  {
    "id": 2,
    "name": "Meera",
    "city": "Chennai",
    "age": 32,
    "salary": 52000
  },
  {
    "id": 3,
    "name": "Rajesh",
    "city": "Bangalore",
    "age": 29,
    "salary": 61000
  },
  {
    "id": 4,
    "name": "Priya",
       "city": "Delhi",
    "age": 22,
    "salary": 38000
  },
  {
    "id": 5,
    "name": "Sanjay",
    "city": "Mumbai",
    "age": 35,
    "salary": 72000
  }]

df_json = spark.createDataFrame(json_data)
df.write.mode("overwrite").json("employees.json")
df_json.show()
df_json.printSchema()

df.write.mode("overwrite").parquet("employees.parquet")

df_parquet=spark.read.parquet("employees.parquet")
df_parquet.show()
